name: KIT-Promotion
description: Request to promote your KIT
title: "[Promote KIT]: "
labels: ["kit-proposal"]
assignees:
  - octocat
body:
  - type: input
    id: Artefact_Location
    attributes:
      label: Contact email
      description: provide a list of links to the required artefacts
    validations:
      required: true